### ISSUE TITLE
error importing in typescript

### ISSUE THREAD

**Issue by cdiaz** [fuse-box/fusedb#1]
![](https://ibin.co/3gmqBDJ21mNs.png "error importing")

Module '"/.../node_modules/fusedb/index"' has no exported member 'FuseDB'. (2305)
Module '"/.../node_modules/fusedb/index"' has no exported member 'FileAdapter'. (2305)

**Comment by nchanged** [comment]
@cdiaz thanks, i haven't really tested the build yet. Will fix it up, and let you know

**Comment by nchanged** [comment]
@cdiaz it has been fixed, and I cooked an example real quick over here
https://github.com/fuse-box/fusedb-example

Feel free to contribute, the project is in a very early stage and it's very interesting ;-)

**Comment by cdiaz** [comment]
Thank you very much, it is an amazing project.
please update the package in npm

**Comment by nchanged** [comment]
It's updated already! Check the example
