### ISSUE TITLE
not getting import values, getting undefined

### ISSUE THREAD

**Issue by devgeektech** [fuse-box/fusedb#4]
FuseDB, FileAdapter are undefined in import { FuseDB, FileAdapter } from "fusedb"
 Field, Model are undefined import { Field, Model } from "fusedb";

Please help i want to use it!!

**Comment by nchanged** [comment]
@devgeektech you sure you are on the latest version?

**Comment by nchanged** [comment]
https://github.com/fuse-box/fusedb-example

**Comment by devgeektech** [comment]
i just do **npm install fusedb** is not it the latest version?

**Comment by nchanged** [comment]
@devgeektech i've published `1.0.0` now `npm install` gets it right

**Comment by nchanged** [comment]
I think now `1.0.1` works as expected
